apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    appName: frontend
    projectName: expense
spec:
  containers:
    - name: frontend
      image: 835817189095.dkr.ecr.us-east-1.amazonaws.com/expense-frontend:2.0.1

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    appName: frontend
    projectName: expense
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80